config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  resources :users
  root "static_pages#home"
  get 'static_pages/help'
  get 'static_pages/about'
  get 'signup'      => 'users#new'
  get 'login'       => "sessions#new"
  post 'login'      => "sessions#create"
  delete 'logout'   => 'sessions#destroy'
  get 'yourprofile' => 'users#yourprofile'

  resources :newsposts,          only: [:create, :destroy]
    

end

app/models/newspost.rb
class Newspost < ActiveRecord::Base
  
	default_scope -> { order(created_at: :desc) }
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  

  has_many :newsposts
  

  attr_accessor :remember_token
	before_save { self.email = email.downcase } #passes a block to the before_save callback and sets the user’s email address to a lower-case
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    validates :password, presence: true, length: {minimum: 6}, allow_nil: true

    has_secure_password # secure password machinery will be 
    					# => implemented using a single Rails method called has_secure_password

   	# Returns the hash digest of the given string.
  	def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end 

    # Forgets a user.
    def forget
      update_attribute(:remember_digest, nil)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
   # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/newsposts_controller.rb
class NewspostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

  	def create
  		@newspost = current_user.newsposts.build(newspost_params)
    	if @newspost.save
      		flash[:success] = "News created!"
      		redirect_to root_url
    	else
      		render 'static_pages/home'
    	end
  	end

  	def destroy
  	end

  	private
  
  	def newspost_params
      params.require(:newspost).permit(:content)
  	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user

  	else
  		flash.now[:danger] = 'Invalid email or password'
  		render 'new'
  	end

  end

  def destroy

  	log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@newspost = current_user.newsposts.build if logged_in?
  end

  def help
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:destroy, :edit , :update, :index]
  before_action :correct_user,   only: [:edit, :update]
#  before_action :admin_user,     only: :destroy


# ---------- for listiong all uswers ------------ 
  def index
    @users = User.paginate(page: params[:page])
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @newsposts = @user.newsposts.paginate(page: params[:page])
    @allpost = Newspost.all.paginate(page: params[:page])
  	#debugger #Debugging
  end

  def yourprofile
    @user = User.find(params[:id])
    @newsposts = @user.newsposts.paginate(page: params[:page])
  end


  def create
  	@user = User.new(strong_params)
  	#debugger
  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to News Bulletin Portal"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(strong_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
#--------------------------- private section ----------------------------- 
  private
  
  def strong_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "please log in"
      redirect_to login_url
    end
  
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end

  
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "News bulletin board application"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
				
end

app/helpers/newsposts_helper.rb
module NewspostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	   def log_in(user)
    	session[:user_id] = user.id
  	 end


     # Redirects to stored location (or to the default).
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end

    # Stores the URL trying to be accessed.
    def store_location
      session[:forwarding_url] = request.url if request.get?
    end  





  	 # Remembers a user in a persistent session.
  	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
  	end

    def current_user?(user)
      user == current_user
    end


  	def forget(user)
	    user.forget
	    cookies.delete(:user_id)
	    cookies.delete(:remember_token)
  	end

  # Returns the current logged-in user (if any).
  	def current_user
  	  	if (user_id = session[:user_id])
      		@current_user ||= User.find_by(id: user_id)
    	elsif (user_id = cookies.signed[:user_id])
      		user = User.find_by(id: user_id)
      		if user && user.authenticated?(cookies[:remember_token])
        		log_in user
        		@current_user = user
      		end
    	end
  	end

  	def logged_in?
    	!current_user.nil?
  	end

  	def log_out
  		forget(current_user)
    	session.delete(:user_id)
    	@current_user = nil
    end

end
	

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	#Why we use helper funcion ?
	#Ans - method defined in any helper file are automatically avaliable in any view file


	def gravatar_for(user, options = { size: 80 })
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    size = options[:size]
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://warm-scrubland-2636.herokuapp.com/">Employee News Bulletin Portal</a>
    by <a href="https://twitter.com/bharose_">RB</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'https://www.healthi.in/about', :target => "_blank"%></li>
      <li><%= link_to "Contact", 'https://www.healthi.in/contactus', :target => "_blank" %></li>
    
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to (image_tag("logo.jpg",size: "120x45", alt: "Healthi")), root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Help",   '#' %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <%end%>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
    	<div class="container">
	    	<% flash.each do |message_type, message| %>
	        	<div class="alert alert-<%= message_type %>"><%= message %></div>
	      	<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %> <!--debugging -->
		<div>

	</body>
</html>

app/views/newsposts/_allpost.html.erb
<% news = Newspost.all %>
news.each do |newspost| do
	<li id="newspost-<%= newspost.id %>">

	  <%= link_to gravatar_for(newspost.user, size: 50), newspost.user %>
	  <span class="user"><%= link_to newspost.user.name, newspost.user %></span>
	  <span class="content"><%= newspost.content %></span>
	  <span class="timestamp">
	    Posted <%= time_ago_in_words(newspost.created_at) %> ago.
	  </span>
	</li>
<% end %>

app/views/newsposts/_newspost.html.erb
<li id="newspost-<%= newspost.id %>">
  <%= link_to gravatar_for(newspost.user, size: 50), newspost.user %>
  <span class="user"><%= link_to newspost.user.name, newspost.user %></span>
  <span class="content"><%= newspost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(newspost.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_newspost_form.html.erb
<%= form_for(@newspost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new Post/ News..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h3><%= current_user.name %></h3>
<span><%= link_to "view my profile", root_path %></span>
<span><%= pluralize(current_user.newsposts.count, "Post") %></span>

app/views/static_pages/about.html.erb
hi helo

app/views/static_pages/help.html.erb
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="newspost_form">
        <%= render 'shared/newspost_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <h1>Welcome to the News Bulletin Portal</h1>

  <h2>

  </h2>
  	<% if !logged_in? %>
 		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %><br />
 		Already User ? <%= link_to " Log in", login_path%>
 	<%end%>
</div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 20 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit page') %>
<h1>Update Your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save chane", class: "btn btn-primary" %>
    <% end %>

    <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
<!--
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
-->
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= render user %>
    </li>
    <br / >
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
   <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
		<h1>
			<%= gravatar_for @user %>
			<%= @user.name %>
		</h1>
	</section>
  </aside>

   <div class="col-md-8">
    <% if @user.newsposts.any? %>
      <h3>Your all <%= @user.newsposts.count %> posts</h3>
      <ol class="microposts">
        <%= render @newsposts %>
      </ol>
      <%= will_paginate @newsposts %>
    <% end %>
  </div>

</div>

app/views/users/yourprofile.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
		<h1>
			<%= gravatar_for @user %>
			<%= @user.name %>
		</h1>
	</section>
  </aside>

  <div class="col-md-8">
    <% if @user.newsposts.any? %>
      <h3>Your all <%= @user.newsposts.count %> posts</h3>
      <ol class="microposts">
        <%= render @newsposts %>
      </ol>
      <%= will_paginate @newsposts %>
    <% end %>
  </div>

</div>